# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VenuesNearByYou' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VenuesNearByYou

	pod 'Alamofire', '~> 4.4'
	pod 'ObjectMapper', '~> 2.2'

  target 'VenuesNearByYouTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VenuesNearByYouUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
